## multichain cross-chain router Protocol
name: "fetch Ink-protocol Total Deposit"

on:
  schedule:
    - cron: "3 11 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: "check codes"
        uses: actions/checkout@master
      - name: "Run fetchInkTotalDeposit.sh" # 执行shell命令文件
        run: bash fetchInkTotalDeposit.sh
